name: Develop PR Check
on:
  pull_request:
    branches: develop

jobs:
  test-project:
    runs-on: ubuntu-latest

    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: NodeJS Settings
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm i --frozen-lockfile

      - name: Build project
        run: npm run build

      - name: Start unit tests
        run: npm run test
